--- # PAuse Module
- hosts: appserver
  become: yes
  remote_user: test
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Disable the apache module in apche2
    apache2_module: state=present name=alias 
