--- # APT Module
- hosts: appserver
  become: yes
  remote_user: test
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Equivalent of apt-get update
    apt: update_cache=yes
  - name: Equivalent of apt-get upgrade
    apt: upgrade=dist

  
