--- # Crontab  Module-  Remember we are running as root so the cron would be added for root not user. So on client first become root and then do crontab -l
- hosts: apacheweb
  become: yes
  remote_user: test
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Add a cron job to the test user
    cron: name="list files" minute="0" hour="1" job="ls -al /etc > /home/test/cronresult.log"
