--- # Service  Module
- hosts: apacheweb
  become: yes
  remote_user: test
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Add a new group called newgroup
    group: name=newgroup state=present
