--- # Service  Module
# Here we are able to change the selinux config file selinux status to disabled and we can test it with the command cat /etc/selinux/config. But if u do sestatus it shows the selinux status enable. So we need to reboot after disabling the selinux in the configuration file
- hosts: apacheweb
  become: yes
  remote_user: test
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Changing SELinux Configuration to Permissive
    selinux: policy=targeted state=permissive
