--- # Service  Module
- hosts: apacheweb
  become: yes
  remote_user: test
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Installing Apache WEb SErver
    action: yum name=httpd state=installed
  - name: Start the web server
    service: name=httpd state=started
  
