--- # Service  Module
- hosts: apacheweb
  become: yes
  remote_user: test
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Exectuing a remote command - uptime
    shell: /bin/uptime >> uptime.log
