--- # User Module
# for testing on the web client do "cat /etc/passwd | grep apache
#Removing the test user created by usermodule1.yml
- hosts: apacheweb
  become: yes
  remote_user: test
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Add the user called tstapache  to the web client
    user: name=tstapache2 state=absent
